export const LOAD_EMPLOYEES = 'LOAD_EMPLOYEES';
export const EMPLOYEES_LOADING = 'EMPLOYEES_LOADING';
export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const LOAD_EMPLOYEES_FAILURE = 'LOAD_EMPLOYEES_FAILURE';